"""Regenerate fig08_dominant_transition_matrices.png (Figure 5.10) from current data.

Added 2026-09-26 in response to an external review that found the LLM panel's stated
n (3,321/3,600) did not match a fresh recomputation of the same "unique dominant on
both sides" rule (3,309/3,600). Root cause: the figure was generated by the old,
superseded scripts/make_figures.py, which read distribution_analysis_v1/hypothesis_
tests/dominant_transition_matrices.csv -- a stale file never refreshed after later
reconciliation. The human panel (338/600) was already correct and is unchanged.

This script re-derives both panels directly from the current, canonical
results/comparison_audit.csv (neutral_tie / persona_tie columns identify texts with a
unique top emotion on each side; winner0 / winner1 give the transition itself), so the
figure has a real, current, reproducible source instead of a stale intermediate CSV.

Updated 2026-09-26 (same day, second pass) in response to a second external review
finding the axis labels and colourbars unreadable at print size: the figure was
included in the thesis at \\includegraphics[width=5.0in] against a native figsize of
20in, a 4x downscale that shrank 13-17pt matplotlib fonts to an effective 3-4pt. Fixed
by (a) shrinking the native figure width to 13in (a ~2.3x downscale against the
document's full \\textwidth of 5.79in, used in place of the previous 5.0in) and
(b) scaling every font (ticks, axis labels, titles, colourbar ticks/labels) up to
compensate, so the effective printed size is comparable to the document's body text.
"""
from pathlib import Path
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd

root = Path(__file__).resolve().parents[2]  # thesis final/ (patched from original sibling-of-script layout)
EMOTIONS = ['anger', 'disgust', 'fear', 'guilt', 'joy', 'pride', 'relief', 'sadness', 'shame', 'surprise', 'trust']

df = pd.read_csv(root / "results/comparison_audit.csv")

fig, axes = plt.subplots(1, 2, figsize=(13, 6.6))
for ax, source in zip(axes, ('Human', 'LLM')):
    sub = df[df['source'] == source]
    unique_dom = sub[(~sub['neutral_tie']) & (~sub['persona_tie'])]
    n_ret = len(unique_dom)
    n_tot = len(sub)
    mat = pd.crosstab(unique_dom['winner0'], unique_dom['winner1'])
    mat = mat.reindex(index=range(11), columns=range(11), fill_value=0)
    im = ax.imshow(mat.values, cmap='viridis', aspect='auto')
    ax.set_xticks(range(11)); ax.set_xticklabels(EMOTIONS, rotation=90, fontsize=20)
    ax.set_yticks(range(11)); ax.set_yticklabels(EMOTIONS, fontsize=20)
    ax.set_title(f"{source.upper()} dominant-emotion transitions", fontsize=19, pad=30)
    ax.text(0.5, 1.035, f"(unique-dominant only, n={n_ret}/{n_tot})", transform=ax.transAxes,
            ha='center', va='bottom', fontsize=14)
    ax.set_xlabel('Persona dominant emotion', fontsize=21)
    ax.set_ylabel('Neutral dominant emotion', fontsize=21)
    cbar = fig.colorbar(im, ax=ax, fraction=0.046)
    cbar.set_label(f'{source} count', fontsize=18)
    cbar.ax.tick_params(labelsize=16)
    print(source, "n_ret:", n_ret, "n_tot:", n_tot)

fig.tight_layout()
out = root / "thesis_document" / "images" / "fig08_dominant_transition_matrices.png"
fig.savefig(out, dpi=200, bbox_inches="tight")
plt.close(fig)
print("saved", out)
